@startuml Mindfulness

+class Program {
  + Main()  : void
}
+class Menu {
  + ShowMenu() : void
}
+class Activity {
' Attributes
  # _activityName     : string
  # _activityDetails  : string
  # _activityDuration : int
  # _spinnerDuration  : int

' Constructors
  + Activity()
  
' Behaviors
  + GetActivityDuration() : int
  + GetStartingMessage()  : void
  + GetEndingMessage()    : void
  + ShowSpinner()         : void
  + CountdownTimer()      : void
}

+class Breathing {
' Attributes
  - _breatheInSecs    : int
  - _breatheHoldSecs  : int
  - _breatheOutSecs   : int

' Constructors
  + Breathing()

' Behaviors
  + GetBreathingSession()   : void 
  - GetBreathingCountdown() : void
}
note bottom of Breathing
  Help the user pace their 
  breathing to have a session 
  of deep breathing for a 
  certain amount of time. 
  They might find more peace 
  and less stress through the 
  exercise.
end note

+class Reflecting {
' Attributes
  - _prompts              : List<strings>
  - _pickedPrompt         : string
  - _reflectingQuestions  : List<string>

' Constructors
  + Reflecting()

' Behaviors
  + GetReflectingSession()  : void
  - GetRandomPrompt()       : void
  - GetRandomQuestion()     : void
}
note bottom of Reflecting
  Guide the user to think deeply, 
  by having them consider a certain 
  experience when they were successful 
  or demonstrated strength. Then, prompt 
  them with questions to reflect more 
  deeply about details of this experience. 
  They might discover more depth than they 
  previously realized.
end note

+class Listing {
' Attributes
  - _prompts          : List<string>
  - _pickedPrompt     : string

' Constructors
  + Listing()

' Behaviors
  + GetListingSession() : void
  - GetRandomPrompt()   : void
  - GetAnswers()        : void
}
note bottom of Listing
  Guide the user to think 
  broadly, by helping them 
  list as many things as 
  they can in a certain area 
  of strength or positivity. 
  They might discover more 
  breadth than they previously 
  realized.
end note

Program <-- Menu
Program <-- Activity
Activity <|-- Breathing
Activity <|-- Reflecting
Activity <|-- Listing

@enduml